// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: p2p.proto

package protocols_p2p

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// designed to be shared between all app protocols
type MessageData struct {
	// shared between all requests
	ClientVersion        string   `protobuf:"bytes,1,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Gossip               bool     `protobuf:"varint,4,opt,name=gossip,proto3" json:"gossip,omitempty"`
	NodeId               string   `protobuf:"bytes,5,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	NodePubKey           []byte   `protobuf:"bytes,6,opt,name=nodePubKey,proto3" json:"nodePubKey,omitempty"`
	Sign                 []byte   `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageData) Reset()         { *m = MessageData{} }
func (m *MessageData) String() string { return proto.CompactTextString(m) }
func (*MessageData) ProtoMessage()    {}
func (*MessageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{0}
}
func (m *MessageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageData.Unmarshal(m, b)
}
func (m *MessageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageData.Marshal(b, m, deterministic)
}
func (m *MessageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageData.Merge(m, src)
}
func (m *MessageData) XXX_Size() int {
	return xxx_messageInfo_MessageData.Size(m)
}
func (m *MessageData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageData.DiscardUnknown(m)
}

var xxx_messageInfo_MessageData proto.InternalMessageInfo

func (m *MessageData) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *MessageData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageData) GetGossip() bool {
	if m != nil {
		return m.Gossip
	}
	return false
}

func (m *MessageData) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *MessageData) GetNodePubKey() []byte {
	if m != nil {
		return m.NodePubKey
	}
	return nil
}

func (m *MessageData) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

// a protocol define a set of reuqest and responses
type GravitationRequest struct {
	MessageData *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	// method specific data
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GravitationRequest) Reset()         { *m = GravitationRequest{} }
func (m *GravitationRequest) String() string { return proto.CompactTextString(m) }
func (*GravitationRequest) ProtoMessage()    {}
func (*GravitationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{1}
}
func (m *GravitationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GravitationRequest.Unmarshal(m, b)
}
func (m *GravitationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GravitationRequest.Marshal(b, m, deterministic)
}
func (m *GravitationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GravitationRequest.Merge(m, src)
}
func (m *GravitationRequest) XXX_Size() int {
	return xxx_messageInfo_GravitationRequest.Size(m)
}
func (m *GravitationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GravitationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GravitationRequest proto.InternalMessageInfo

func (m *GravitationRequest) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *GravitationRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GravitationResponse struct {
	MessageData *MessageData `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	// response specific data
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GravitationResponse) Reset()         { *m = GravitationResponse{} }
func (m *GravitationResponse) String() string { return proto.CompactTextString(m) }
func (*GravitationResponse) ProtoMessage()    {}
func (*GravitationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{2}
}
func (m *GravitationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GravitationResponse.Unmarshal(m, b)
}
func (m *GravitationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GravitationResponse.Marshal(b, m, deterministic)
}
func (m *GravitationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GravitationResponse.Merge(m, src)
}
func (m *GravitationResponse) XXX_Size() int {
	return xxx_messageInfo_GravitationResponse.Size(m)
}
func (m *GravitationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GravitationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GravitationResponse proto.InternalMessageInfo

func (m *GravitationResponse) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *GravitationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageData)(nil), "protocols.p2p.MessageData")
	proto.RegisterType((*GravitationRequest)(nil), "protocols.p2p.GravitationRequest")
	proto.RegisterType((*GravitationResponse)(nil), "protocols.p2p.GravitationResponse")
}

func init() { proto.RegisterFile("p2p.proto", fileDescriptor_e7fdddb109e6467a) }

var fileDescriptor_e7fdddb109e6467a = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0x77, 0xed, 0xda, 0xa9, 0xeb, 0x61, 0x04, 0x09, 0x22, 0x52, 0x8a, 0x87, 0x9e,
	0x7a, 0xa8, 0x57, 0x8f, 0x82, 0x88, 0x08, 0x92, 0x83, 0xf7, 0xec, 0x76, 0x28, 0x81, 0x36, 0x89,
	0x9d, 0xac, 0xe0, 0x03, 0xfa, 0x5e, 0xb2, 0xa1, 0xb2, 0xed, 0x03, 0x78, 0xca, 0xfc, 0x5f, 0x26,
	0x19, 0xbe, 0x81, 0xcc, 0x37, 0xbe, 0xf6, 0xa3, 0x0b, 0x0e, 0xb7, 0xf1, 0xd8, 0xbb, 0x9e, 0x6b,
	0xdf, 0xf8, 0xf2, 0x47, 0x40, 0xfe, 0x46, 0xcc, 0xba, 0xa3, 0x27, 0x1d, 0x34, 0xde, 0xc3, 0x76,
	0xdf, 0x1b, 0xb2, 0xe1, 0x83, 0x46, 0x36, 0xce, 0x4a, 0x51, 0x88, 0x2a, 0x53, 0x4b, 0x88, 0xb7,
	0x90, 0x05, 0x33, 0x10, 0x07, 0x3d, 0x78, 0x99, 0x14, 0xa2, 0x5a, 0xa9, 0x13, 0xc0, 0x4b, 0x48,
	0x4c, 0x2b, 0x57, 0xf1, 0x61, 0x62, 0x5a, 0xbc, 0x86, 0xb4, 0x73, 0xcc, 0xc6, 0xcb, 0x75, 0x21,
	0xaa, 0x73, 0x35, 0xa5, 0x23, 0xb7, 0xae, 0xa5, 0x97, 0x56, 0x9e, 0xc5, 0xde, 0x29, 0xe1, 0x1d,
	0xc0, 0xb1, 0x7a, 0x3f, 0xec, 0x5e, 0xe9, 0x5b, 0xa6, 0x85, 0xa8, 0x2e, 0xd4, 0x8c, 0x20, 0xc2,
	0x9a, 0x4d, 0x67, 0xe5, 0x26, 0xde, 0xc4, 0xba, 0xec, 0x01, 0x9f, 0x47, 0xfd, 0x65, 0x82, 0x0e,
	0xc6, 0x59, 0x45, 0x9f, 0x07, 0xe2, 0x80, 0x8f, 0x90, 0x0f, 0x27, 0xb9, 0xe8, 0x92, 0x37, 0x37,
	0xf5, 0x62, 0x05, 0xf5, 0x4c, 0x5f, 0xcd, 0xdb, 0x51, 0xc2, 0x66, 0x8a, 0xd1, 0x31, 0x53, 0x7f,
	0xb1, 0x1c, 0xe0, 0x6a, 0x31, 0x8d, 0xbd, 0xb3, 0x4c, 0xff, 0x35, 0x6e, 0x97, 0xc6, 0x1f, 0x1e,
	0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x00, 0xf4, 0x0d, 0x4f, 0xc7, 0x01, 0x00, 0x00,
}
