// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: p2p.proto

package protocols_p2p

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// designed to be shared between all app protocols
type MessageData struct {
	// shared between all requests
	ClientVersion        string   `protobuf:"bytes,1,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Gossip               bool     `protobuf:"varint,4,opt,name=gossip,proto3" json:"gossip,omitempty"`
	NodeId               string   `protobuf:"bytes,5,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	NodePubKey           []byte   `protobuf:"bytes,6,opt,name=nodePubKey,proto3" json:"nodePubKey,omitempty"`
	Sign                 []byte   `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageData) Reset()         { *m = MessageData{} }
func (m *MessageData) String() string { return proto.CompactTextString(m) }
func (*MessageData) ProtoMessage()    {}
func (*MessageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{0}
}
func (m *MessageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageData.Unmarshal(m, b)
}
func (m *MessageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageData.Marshal(b, m, deterministic)
}
func (m *MessageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageData.Merge(m, src)
}
func (m *MessageData) XXX_Size() int {
	return xxx_messageInfo_MessageData.Size(m)
}
func (m *MessageData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageData.DiscardUnknown(m)
}

var xxx_messageInfo_MessageData proto.InternalMessageInfo

func (m *MessageData) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *MessageData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MessageData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageData) GetGossip() bool {
	if m != nil {
		return m.Gossip
	}
	return false
}

func (m *MessageData) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *MessageData) GetNodePubKey() []byte {
	if m != nil {
		return m.NodePubKey
	}
	return nil
}

func (m *MessageData) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *GravitationRequest) Reset()         { *m = GravitationRequest{} }
func (m *GravitationRequest) String() string { return proto.CompactTextString(m) }
func (*GravitationRequest) ProtoMessage()    {}
func (*GravitationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{1}
}
func (m *GravitationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GravitationRequest.Unmarshal(m, b)
}
func (m *GravitationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GravitationRequest.Marshal(b, m, deterministic)
}
func (m *GravitationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GravitationRequest.Merge(m, src)
}
func (m *GravitationRequest) XXX_Size() int {
	return xxx_messageInfo_GravitationRequest.Size(m)
}
func (m *GravitationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GravitationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GravitationRequest proto.InternalMessageInfo

func (m *GravitationRequest) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *GravitationRequest) GetProfile() []*GravitationRequest_Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *GravitationRequest) GetSubOrbit() []*GravitationRequest_SubOrbit {
	if m != nil {
		return m.SubOrbit
	}
	return nil
}

// method specific data
type GravitationRequest_Profile struct {
	Item                 string   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GravitationRequest_Profile) Reset()         { *m = GravitationRequest_Profile{} }
func (m *GravitationRequest_Profile) String() string { return proto.CompactTextString(m) }
func (*GravitationRequest_Profile) ProtoMessage()    {}
func (*GravitationRequest_Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{1, 0}
}
func (m *GravitationRequest_Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GravitationRequest_Profile.Unmarshal(m, b)
}
func (m *GravitationRequest_Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GravitationRequest_Profile.Marshal(b, m, deterministic)
}
func (m *GravitationRequest_Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GravitationRequest_Profile.Merge(m, src)
}
func (m *GravitationRequest_Profile) XXX_Size() int {
	return xxx_messageInfo_GravitationRequest_Profile.Size(m)
}
func (m *GravitationRequest_Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_GravitationRequest_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_GravitationRequest_Profile proto.InternalMessageInfo

func (m *GravitationRequest_Profile) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

type GravitationRequest_SubOrbit struct {
	PeerId               string                        `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Profile              []*GravitationRequest_Profile `protobuf:"bytes,2,rep,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GravitationRequest_SubOrbit) Reset()         { *m = GravitationRequest_SubOrbit{} }
func (m *GravitationRequest_SubOrbit) String() string { return proto.CompactTextString(m) }
func (*GravitationRequest_SubOrbit) ProtoMessage()    {}
func (*GravitationRequest_SubOrbit) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{1, 1}
}
func (m *GravitationRequest_SubOrbit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GravitationRequest_SubOrbit.Unmarshal(m, b)
}
func (m *GravitationRequest_SubOrbit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GravitationRequest_SubOrbit.Marshal(b, m, deterministic)
}
func (m *GravitationRequest_SubOrbit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GravitationRequest_SubOrbit.Merge(m, src)
}
func (m *GravitationRequest_SubOrbit) XXX_Size() int {
	return xxx_messageInfo_GravitationRequest_SubOrbit.Size(m)
}
func (m *GravitationRequest_SubOrbit) XXX_DiscardUnknown() {
	xxx_messageInfo_GravitationRequest_SubOrbit.DiscardUnknown(m)
}

var xxx_messageInfo_GravitationRequest_SubOrbit proto.InternalMessageInfo

func (m *GravitationRequest_SubOrbit) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *GravitationRequest_SubOrbit) GetProfile() []*GravitationRequest_Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type GravitationResponse struct {
	MessageData          *MessageData                    `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	Profile              []*GravitationResponse_Profile  `protobuf:"bytes,2,rep,name=profile,proto3" json:"profile,omitempty"`
	SubOrbit             []*GravitationResponse_SubOrbit `protobuf:"bytes,3,rep,name=sub_orbit,json=subOrbit,proto3" json:"sub_orbit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *GravitationResponse) Reset()         { *m = GravitationResponse{} }
func (m *GravitationResponse) String() string { return proto.CompactTextString(m) }
func (*GravitationResponse) ProtoMessage()    {}
func (*GravitationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{2}
}
func (m *GravitationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GravitationResponse.Unmarshal(m, b)
}
func (m *GravitationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GravitationResponse.Marshal(b, m, deterministic)
}
func (m *GravitationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GravitationResponse.Merge(m, src)
}
func (m *GravitationResponse) XXX_Size() int {
	return xxx_messageInfo_GravitationResponse.Size(m)
}
func (m *GravitationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GravitationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GravitationResponse proto.InternalMessageInfo

func (m *GravitationResponse) GetMessageData() *MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (m *GravitationResponse) GetProfile() []*GravitationResponse_Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *GravitationResponse) GetSubOrbit() []*GravitationResponse_SubOrbit {
	if m != nil {
		return m.SubOrbit
	}
	return nil
}

// method specific data
type GravitationResponse_Profile struct {
	Item                 string   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GravitationResponse_Profile) Reset()         { *m = GravitationResponse_Profile{} }
func (m *GravitationResponse_Profile) String() string { return proto.CompactTextString(m) }
func (*GravitationResponse_Profile) ProtoMessage()    {}
func (*GravitationResponse_Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{2, 0}
}
func (m *GravitationResponse_Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GravitationResponse_Profile.Unmarshal(m, b)
}
func (m *GravitationResponse_Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GravitationResponse_Profile.Marshal(b, m, deterministic)
}
func (m *GravitationResponse_Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GravitationResponse_Profile.Merge(m, src)
}
func (m *GravitationResponse_Profile) XXX_Size() int {
	return xxx_messageInfo_GravitationResponse_Profile.Size(m)
}
func (m *GravitationResponse_Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_GravitationResponse_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_GravitationResponse_Profile proto.InternalMessageInfo

func (m *GravitationResponse_Profile) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

type GravitationResponse_SubOrbit struct {
	PeerId               string                         `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Profile              []*GravitationResponse_Profile `protobuf:"bytes,2,rep,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GravitationResponse_SubOrbit) Reset()         { *m = GravitationResponse_SubOrbit{} }
func (m *GravitationResponse_SubOrbit) String() string { return proto.CompactTextString(m) }
func (*GravitationResponse_SubOrbit) ProtoMessage()    {}
func (*GravitationResponse_SubOrbit) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{2, 1}
}
func (m *GravitationResponse_SubOrbit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GravitationResponse_SubOrbit.Unmarshal(m, b)
}
func (m *GravitationResponse_SubOrbit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GravitationResponse_SubOrbit.Marshal(b, m, deterministic)
}
func (m *GravitationResponse_SubOrbit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GravitationResponse_SubOrbit.Merge(m, src)
}
func (m *GravitationResponse_SubOrbit) XXX_Size() int {
	return xxx_messageInfo_GravitationResponse_SubOrbit.Size(m)
}
func (m *GravitationResponse_SubOrbit) XXX_DiscardUnknown() {
	xxx_messageInfo_GravitationResponse_SubOrbit.DiscardUnknown(m)
}

var xxx_messageInfo_GravitationResponse_SubOrbit proto.InternalMessageInfo

func (m *GravitationResponse_SubOrbit) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *GravitationResponse_SubOrbit) GetProfile() []*GravitationResponse_Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageData)(nil), "protocols.p2p.MessageData")
	proto.RegisterType((*GravitationRequest)(nil), "protocols.p2p.GravitationRequest")
	proto.RegisterType((*GravitationRequest_Profile)(nil), "protocols.p2p.GravitationRequest.Profile")
	proto.RegisterType((*GravitationRequest_SubOrbit)(nil), "protocols.p2p.GravitationRequest.SubOrbit")
	proto.RegisterType((*GravitationResponse)(nil), "protocols.p2p.GravitationResponse")
	proto.RegisterType((*GravitationResponse_Profile)(nil), "protocols.p2p.GravitationResponse.Profile")
	proto.RegisterType((*GravitationResponse_SubOrbit)(nil), "protocols.p2p.GravitationResponse.SubOrbit")
}

func init() { proto.RegisterFile("p2p.proto", fileDescriptor_e7fdddb109e6467a) }

var fileDescriptor_e7fdddb109e6467a = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x49, 0xd2, 0x37, 0x69, 0x26, 0x6f, 0x3d, 0xac, 0xa0, 0x4b, 0x51, 0x09, 0xc5, 0x43,
	0x54, 0xc8, 0x21, 0x5e, 0xbd, 0x59, 0xa8, 0x45, 0xc4, 0xb2, 0x82, 0xd7, 0x92, 0x34, 0x6b, 0x5d,
	0x68, 0xb2, 0x6b, 0x76, 0x23, 0xf8, 0x01, 0xfd, 0x30, 0x1e, 0xfc, 0x0e, 0x92, 0x6d, 0x4a, 0xff,
	0x04, 0xb4, 0x62, 0x4f, 0x99, 0x99, 0xcc, 0xf3, 0x4c, 0x9e, 0x5f, 0xc0, 0x15, 0x91, 0x08, 0x45,
	0xc1, 0x15, 0x47, 0x1d, 0xfd, 0x98, 0xf0, 0x99, 0x0c, 0x45, 0x24, 0x7a, 0xef, 0x06, 0x78, 0x77,
	0x54, 0xca, 0x78, 0x4a, 0xfb, 0xb1, 0x8a, 0xd1, 0x29, 0x74, 0x26, 0x33, 0x46, 0x73, 0xf5, 0x48,
	0x0b, 0xc9, 0x78, 0x8e, 0x0d, 0xdf, 0x08, 0x5c, 0xb2, 0x3e, 0x44, 0x47, 0xe0, 0x2a, 0x96, 0x51,
	0xa9, 0xe2, 0x4c, 0x60, 0xd3, 0x37, 0x02, 0x8b, 0x2c, 0x07, 0x68, 0x0f, 0x4c, 0x96, 0x62, 0x4b,
	0x0b, 0x4d, 0x96, 0xa2, 0x03, 0xb0, 0xa7, 0x5c, 0x4a, 0x26, 0x70, 0xcb, 0x37, 0x82, 0x36, 0xa9,
	0xbb, 0x6a, 0x9e, 0xf3, 0x94, 0x0e, 0x53, 0xfc, 0x4f, 0xef, 0xd6, 0x1d, 0x3a, 0x01, 0xa8, 0xaa,
	0x51, 0x99, 0xdc, 0xd2, 0x37, 0x6c, 0xfb, 0x46, 0xf0, 0x9f, 0xac, 0x4c, 0x10, 0x82, 0x96, 0x64,
	0xd3, 0x1c, 0x3b, 0xfa, 0x8d, 0xae, 0x7b, 0x1f, 0x26, 0xa0, 0x41, 0x11, 0xbf, 0x32, 0x15, 0x2b,
	0xc6, 0x73, 0x42, 0x5f, 0x4a, 0x2a, 0x15, 0xba, 0x02, 0x2f, 0x5b, 0xa6, 0xd3, 0x61, 0xbc, 0xa8,
	0x1b, 0xae, 0x31, 0x08, 0x57, 0xf2, 0x93, 0xd5, 0x75, 0x74, 0x0d, 0x8e, 0x28, 0xf8, 0x13, 0x9b,
	0x51, 0x6c, 0xfa, 0x56, 0xe0, 0x45, 0x67, 0x1b, 0xca, 0xe6, 0xc5, 0x70, 0x34, 0x17, 0x90, 0x85,
	0x12, 0x0d, 0xc0, 0x95, 0x65, 0x32, 0xe6, 0x45, 0xc2, 0x14, 0xb6, 0xb4, 0xcd, 0xf9, 0xcf, 0x36,
	0x0f, 0x65, 0x72, 0x5f, 0x29, 0x48, 0x5b, 0xd6, 0x55, 0xf7, 0x18, 0x9c, 0xda, 0xbc, 0x22, 0xc0,
	0x14, 0xcd, 0xea, 0x9f, 0xa3, 0xeb, 0xee, 0x33, 0xb4, 0x17, 0x22, 0x74, 0x08, 0x8e, 0xa0, 0xb4,
	0x18, 0xb3, 0xb4, 0x5e, 0xb1, 0xab, 0x76, 0x98, 0xee, 0x24, 0x51, 0xef, 0xd3, 0x84, 0xfd, 0xb5,
	0x3d, 0x29, 0x78, 0x2e, 0xe9, 0x1f, 0x61, 0xf7, 0x37, 0x3f, 0xed, 0x5b, 0x4a, 0xf3, 0x93, 0x4d,
	0xda, 0x37, 0x4d, 0xda, 0x17, 0x5b, 0xf8, 0xfc, 0x1e, 0x37, 0xdb, 0x06, 0xf7, 0x4e, 0x32, 0x25,
	0xb6, 0xd6, 0x5c, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x09, 0xa4, 0x6d, 0xd2, 0xc6, 0x03, 0x00,
	0x00,
}
